### ISSUE TITLE
Augmentation dots for rests are not yet annotated

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#23]
Though augmentation dots for note heads are annotated, those for rests are not.
How come?
This impacts measure correctness, hence a fix is needed

**Comment by nasehim7** [comment]
Implementation Done. Rest dots will be there from now onwards. For reference, control image generated from a score containing rest dots had this:
<img width="95" alt="screen shot 2018-05-16 at 5 43 23 pm" src="https://user-images.githubusercontent.com/18035782/40120052-e71708d4-593b-11e8-9e44-50a9f3b7d5e5.png">
Is it good enough? :)

**Comment by hbitteur** [comment]
Perfect, thanks!
