### ISSUE TITLE
Repeat dots are not yet annotated

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#24]
We need examples for all the various meanings of dots.

**Comment by nasehim7** [comment]
<img width="1172" alt="screen shot 2018-05-19 at 2 58 11 pm" src="https://user-images.githubusercontent.com/18035782/40267126-1cda5d00-5b75-11e8-8acf-f6bb114dbc3c.png">
Is this the kind of output we want after resolving this issue? :)

**Comment by hbitteur** [comment]
@nasehim7 Perhaps I don't really understand your question

My position is that reference data should cover as much configurations as possible.
This include the repeat signs.
In this example, there are 2 repeat signs, one left and one right.
For each of them, try to provide the outer compound (such as left repeat sign) and its inner members (thick barline, thin barline, top repeat dot, bottom repeat dot).
Sorry, I'm writing this away from my computer, I don't have the exact symbol names at hand.

**Comment by nasehim7** [comment]
@hbitteur No problem, I got it. We want a nested approach in this one too. Working on it, currently, I'm done with getting the outer element which can be seen in the above control image. Will get back soon. :)

**Comment by nasehim7** [comment]
I did the nesting part. For Reference, Below are the control images:
<img width="124" alt="screen shot 2018-05-20 at 1 59 19 am" src="https://user-images.githubusercontent.com/18035782/40272818-b3dbe99c-5bd1-11e8-9c37-51a4e858a9a7.png">
<img width="106" alt="screen shot 2018-05-20 at 1 59 31 am" src="https://user-images.githubusercontent.com/18035782/40272819-b4f4432e-5bd1-11e8-883e-dbc65a64a5f8.png">
Hope it is in sync with what we want for the OMR. @hbitteur @lasconic

**Comment by hbitteur** [comment]
This looks OK, thanks

**Comment by nasehim7** [comment]
@hbitteur what exactly are the names of these thick and thin barlines? :)

**Comment by lasconic** [comment]
You can use the SMuFL names : http://www.smufl.org/version/latest/range/barlines/

**Comment by nasehim7** [comment]
@hbitteur @lasconic I think now the implementation is more refined than the previous one. Below are the control images: 
<img width="113" alt="screen shot 2018-05-22 at 12 33 41 am" src="https://user-images.githubusercontent.com/18035782/40324958-d60ff15c-5d57-11e8-8c6c-080810ee7329.png">

<img width="130" alt="screen shot 2018-05-22 at 12 06 40 am" src="https://user-images.githubusercontent.com/18035782/40324138-40a5201c-5d55-11e8-8e91-e28bf969e5dd.png">

I have added the commit to the existing PR. Hope it suits well. :)

**Comment by nasehim7** [comment]
@lasconic Should we close this too? It will be good in the next dataset. :)
