### ISSUE TITLE
No example for Staccato dot at all

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#25]
I didn't find any staccato dot in the .xml files.
Are they not correctly addressed by the export software?
Or simply, these symbols don't show up in any sheet you exported?

**Comment by nasehim7** [comment]
Hi @hbitteur 
I tried reconstructing the issue. I placed a staccato below and Staccatissimo above in a score. After that when I generated the XML, I got : 
  ```
<Symbol interline="20" shape="Staccatissimo stroke above">
    <Bounds x="143.882" y="60.864" w="0.626" h="3.781"/>
    </Symbol>
  <Symbol interline="20" shape="Staccato below">
    <Bounds x="240.822" y="271.280" w="3.984" h="3.984"/>
    </Symbol>
```
in the file. I made no implementation changes. Let's discuss on what I am missing here or is it working fine? :)

**Comment by lasconic** [comment]
I guess shape should contain a SMuFL id instead of an english string ?

**Comment by nasehim7** [comment]
The implementation converts Id to string like 
``const Articulation* a = toArticulation(e);
    SymId symId = a->symId();
    QString symName = Sym::id2userName(symId);
    writeData(xml, mag, a->mag(), symName, a);``
The symbol name is sent to the function which writes it in the XML file. The implementation is same for some of the element types like Articulation, Clef etc. in the edata.cpp.

**Comment by lasconic** [comment]
id2userName should be id2name

**Comment by nasehim7** [comment]
Okay making the changes for all other element types accordingly. :)

**Comment by nasehim7** [comment]
Staccatos are fine. Will be available in the next dataset. For reference, below are the control images:
<img width="53" alt="screen shot 2018-05-14 at 4 05 24 pm" src="https://user-images.githubusercontent.com/18035782/39992566-d6c6e0a0-5790-11e8-9699-47cd7dd46628.png">
<img width="58" alt="screen shot 2018-05-14 at 4 05 31 pm" src="https://user-images.githubusercontent.com/18035782/39992580-dd607aa2-5790-11e8-88ae-4417849032b7.png">
