### ISSUE TITLE
No Brace annotation yet

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#26]
There is yet no annotation for brace.
Although a brace is not, strictly speaking, a fixed-shape symbol, we think that the patch classifier might be able to recognize it, when pointed on brace area center.
Hence the need for brace annotation.

**Comment by nasehim7** [comment]
Implemented Bracket Annotations: https://github.com/musescore/MuseScore/pull/3669/commits :)
For reference, a control image is given below:
<img width="65" alt="screen shot 2018-05-14 at 3 58 50 pm" src="https://user-images.githubusercontent.com/18035782/39992269-dc145b4c-578f-11e8-802c-2de3e1829772.png">
:

**Comment by hbitteur** [comment]
For me, this image is a brace, not a bracket.

**Comment by lasconic** [comment]
MuseScore uses the same class for all 4 different types of "brackets". Brace is one of them.

![capture d ecran 2018-05-14 12 41 29](https://user-images.githubusercontent.com/234271/39992792-2c33255c-5774-11e8-964c-4ea1e905f3e8.png)

@nasehim7 can you test the 4 of them ?

**Comment by nasehim7** [comment]
Yes, it is a brace. For reference, we have a normal bracket like this:
<img width="117" alt="screen shot 2018-05-14 at 4 11 25 pm" src="https://user-images.githubusercontent.com/18035782/39992832-a495cde8-5791-11e8-9f8b-a4a4b52d609a.png">

**Comment by hbitteur** [comment]
For Audiveris, these are two different classes.

Braces are very important because they govern the recognition of multi-staff parts, whereas brackets don't (they only convey a grouping meaning).

What does SmuFL say about these 2 kinds of entities?

**Comment by hbitteur** [comment]
IIRC, we decided to introduce Brace in the OMR dataset catalog (even though they are not fixed in shape) because we guess that the classifier will be able to recognize them.

You can introduce Bracket as well, as long as the symbol can be differentiated from the Brace symbol in some way.

**Comment by lasconic** [comment]
@nasehim7 what's the XML for the two images you posted?

**Comment by lasconic** [comment]
```
"brace"
"bracketNormal" 
"bracketSquare" 
"bracketLine"
```
Looks good.

**Comment by lasconic** [comment]
![bracket_test-1](https://user-images.githubusercontent.com/234271/39995136-c58f7f6e-577b-11e8-842b-ce00d7246c5a.png)

**Comment by nasehim7** [comment]
@lasconic Thanks :)
