### ISSUE TITLE
Simple image URLs

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#30]
All annotations files in MuseScore delivery have an Image URL element like "file:outomr/somefile.png".
The "outomr" prefix does not mean anything on my local computer, and this defeats the purpose of an absolute URL.

For the time being, could we stick to relative URLs such as "somefile.png", which will be simply resolved as a sibling of the annotation file? (which is the case in fact)

**Comment by nasehim7** [comment]
So this basically means that instead of the XML having this line:
```
<Image>file:happy-1.png</Image>
```
It should have this:
```
<Image>happy-1.png</Image>
```
so that OMR is able to make a link between the generated PNG and the XML file, right? :)

**Comment by hbitteur** [comment]
You are right.
For the time being, the URL mechanism does not really work. So, the workaround is to locate the .png and the .xml in the same folder, and use just the name of the (sibling) other file.

**Comment by nasehim7** [comment]
Won't be an issue from now onwards. Done. :)
