### ISSUE TITLE
Different staff heights

### ISSUE THREAD

**Issue by hbitteur** [Audiveris/omr-dataset-tools#4]
To normalize the dataset, we need a way to relate any symbol with its scaling information. The current XML format of Annotations does not support different staff heights in the same page.

The proposed modification is to wrap `Symbol` elements in a `Symbols` container with a `spatium`attribute. If the page contains several staff heights, the corresponding Annotations will simply contain several `Symbols` fragments.

**Comment by lasconic** [comment]
Werner counter proposal
* Don't wrap with Symbols 
* Instead add a `spatium` (or `interline`, see #13) attribute per Symbol

Hervé is fine with it. So we have winner.
